In [2]:
import numpy as np

import pandas as pd

In [3]:
data=pd.read_csv("/content/market_data (1).csv")

In [4]:
data.head()

   youtube  facebook  newspaper  sales
0    84.72     19.20      48.96  12.60
1   351.48     33.96      51.84  25.68
2   135.48     20.88      46.32  14.28
3   116.64      1.80      36.00  11.52
4   318.72     24.00       0.36  20.88

In [5]:
y=data["sales"]

In [6]:
y

0      12.60
1      25.68
2      14.28
3      11.52
4      20.88
       ...
166     9.12
167    11.64
168    15.36
169    30.60
170    16.08
Name: sales, Length: 171, dtype: float64

In [13]:
after=data.drop('sales',axis=1).to_numpy()

In [15]:
after.shape

(171, 3)

In [18]:
x1,x2,x3=data["youtube"],data["facebook"],data["newspaper"]

In [22]:
n=len(x1)
x_baias=np.ones((n,1))

In [26]:
final=np.append(x_baias,after,axis=1)

In [27]:
final

array([[  1.  ,  84.72,  19.2 ,  48.96],
       [  1.  , 351.48,  33.96,  51.84],
       [  1.  , 135.48,  20.88,  46.32],
       [  1.  , 116.64,   1.8 ,  36.  ],
       [  1.  , 318.72,  24.  ,   0.36],
       [  1.  , 114.84,   1.68,   8.88],
       [  1.  , 348.84,   4.92,  10.2 ],
       [  1.  , 320.28,  52.56,   6.  ],
       [  1.  ,  89.64,  59.28,  54.84],
       [  1.  ,  51.72,  32.04,  42.12],
       [  1.  , 273.6 ,  45.24,  38.4 ],
       [  1.  , 243.  ,  26.76,  37.92],
       [  1.  , 212.4 ,  40.08,  46.44],
       [  1.  , 352.32,  33.24,   2.16],
       [  1.  , 248.28,  10.08,  31.68],
       [  1.  ,  30.12,  30.84,  51.96],
       [  1.  , 210.12,  27.  ,  37.8 ],
       [  1.  , 107.64,  11.88,  42.84],
       [  1.  , 287.88,  49.8 ,  22.2 ],
       [  1.  , 272.64,  18.96,  59.88],
       [  1.  ,  80.28,  14.04,  44.16],
       [  1.  , 239.76,   3.72,  41.52],
       [  1.  , 120.48,  11.52,   4.32],
       [  1.  , 259.68,  50.04,  47.52],
       [  1.  , 219.12,  55.44,  70.44],
       [  1.  , 315.24,  34.56,  19.08],
       [  1.  , 238.68,  59.28,  72.  ],
       [  1.  ,   8.76,  33.72,  49.68],
       [  1.  , 163.44,  23.04,  19.92],
       [  1.  , 252.96,  59.52,  45.24],
       [  1.  , 252.84,  35.4 ,  11.16],
       [  1.  ,  64.2 ,   2.4 ,  25.68],
       [  1.  , 313.56,  51.24,  65.64],
       [  1.  , 287.16,  18.6 ,  32.76],
       [  1.  , 123.24,  35.52,  10.08],
       [  1.  , 157.32,  51.36,  34.68],
       [  1.  ,  82.8 ,  11.16,   1.08],
       [  1.  ,  37.8 ,  29.52,   2.64],
       [  1.  , 167.16,  17.4 ,  12.24],
       [  1.  , 284.88,  33.  ,  13.2 ],
       [  1.  , 260.16,  52.68,  32.64],
       [  1.  , 238.92,  36.72,  46.44],
       [  1.  , 131.76,  17.16,  38.04],
       [  1.  ,  32.16,  39.6 ,  23.16],
       [  1.  , 155.28,   6.84,  37.56],
       [  1.  , 256.08,  29.52,  15.72],
       [  1.  ,  20.28,  52.44, 107.28],
       [  1.  ,  33.  ,   1.92,  24.84],
       [  1.  , 144.6 ,  34.2 ,  17.04],
       [  1.  ,   6.48,  35.88,  11.28],
       [  1.  , 139.2 ,   9.24,  27.72],
       [  1.  ,  91.68,  32.04,  26.76],
       [  1.  , 287.76,   4.92,  44.28],
       [  1.  ,  90.36,  24.36,  39.  ],
       [  1.  ,  82.08,  53.4 ,  42.72],
       [  1.  , 256.2 ,  51.6 ,  40.56],
       [  1.  , 231.84,  22.08,  78.84],
       [  1.  ,  91.56,  33.  ,  19.2 ],
       [  1.  , 132.84,  48.72,  75.84],
       [  1.  , 105.96,  30.6 ,  88.08],
       [  1.  , 131.76,  57.36,  61.68],
       [  1.  , 161.16,   5.88,  11.16],
       [  1.  ,  34.32,   1.8 ,  39.6 ],
       [  1.  , 261.24,  40.2 ,  70.8 ],
       [  1.  , 301.08,  43.8 ,  86.76],
       [  1.  , 128.88,  16.8 ,  13.08],
       [  1.  , 195.96,  37.92,  63.48],
       [  1.  , 237.12,   4.2 ,   7.08],
       [  1.  , 221.88,  25.2 ,  26.4 ],
       [  1.  , 347.64,  50.76,  61.44],
       [  1.  , 162.24,  50.04,  55.08],
       [  1.  , 266.88,   5.16,  59.76],
       [  1.  , 355.68,  43.56, 121.08],
       [  1.  , 336.24,  12.12,  25.68],
       [  1.  , 225.48,  20.64,  21.48],
       [  1.  , 285.84,  41.16,   6.36],
       [  1.  , 165.48,  55.68,  70.8 ],
       [  1.  ,  30.  ,  13.2 ,  35.64],
       [  1.  , 108.48,   0.36,  27.84],
       [  1.  ,  15.72,   0.48,  30.72],
       [  1.  , 306.48,  32.28,   6.6 ],
       [  1.  , 270.96,   9.84,  67.8 ],
       [  1.  , 290.04,  45.6 ,  27.84],
       [  1.  , 210.84,  18.48,   2.88],
       [  1.  , 251.52,  24.72,  12.84],
       [  1.  ,  93.84,  56.16,  41.4 ],
       [  1.  ,  90.12,  42.  ,  63.24],
       [  1.  , 167.04,  17.16,  30.72],
       [  1.  ,  91.68,   0.96,  17.76],
       [  1.  , 150.84,  44.28,  95.04],
       [  1.  ,  23.28,  19.2 ,  26.76],
       [  1.  , 169.56,  32.16,  55.44],
       [  1.  ,  22.56,  26.04,  60.48],
       [  1.  , 268.8 ,   2.88,  18.72],
       [  1.  , 147.72,  41.52,  14.88],
       [  1.  , 275.4 ,  38.76,  89.04],
       [  1.  , 104.64,  14.16,  31.08],
       [  1.  ,   9.36,  46.68,  60.72],
       [  1.  ,  96.24,   0.  ,  11.04],
       [  1.  , 264.36,  58.8 ,   3.84],
       [  1.  ,  71.52,  14.4 ,  51.72],
       [  1.  ,   0.84,  47.52,  10.44],
       [  1.  , 318.24,   3.48,  51.6 ],
       [  1.  ,  10.08,  32.64,   2.52],
       [  1.  , 263.76,  40.2 ,  54.12],
       [  1.  ,  44.28,  46.32,  78.72],
       [  1.  ,  57.96,  56.4 ,  10.2 ],
       [  1.  ,  30.72,  46.8 ,  11.16],
       [  1.  , 328.44,  34.68,  71.64],
       [  1.  ,  51.6 ,  31.08,  24.6 ],
       [  1.  , 221.88,  52.68,   2.04],
       [  1.  ,  88.08,  20.4 ,  15.48],
       [  1.  , 232.44,  42.48,  90.72],
       [  1.  , 264.6 ,  39.84,  45.48],
       [  1.  , 125.52,   6.84,  41.28],
       [  1.  , 115.44,  17.76,  46.68],
       [  1.  , 168.36,   2.28,  10.8 ],
       [  1.  , 288.12,   8.76,  10.44],
       [  1.  , 291.84,  58.8 ,  53.16],
       [  1.  ,  45.6 ,  48.36,  14.28],
       [  1.  ,  53.64,  30.96,  24.72],
       [  1.  , 336.84,  16.68,  44.4 ],
       [  1.  , 145.2 ,  10.08,  58.44],
       [  1.  , 237.12,  27.96,  17.04],
       [  1.  , 205.56,  47.64,  45.24],
       [  1.  , 225.36,  25.32,  11.4 ],
       [  1.  ,   4.92,  13.92,   6.84],
       [  1.  , 112.68,  52.2 ,  60.6 ],
       [  1.  , 179.76,   1.56,  29.16],
       [  1.  ,  14.04,  44.28,  54.24],
       [  1.  , 158.04,  22.08,  41.52],
       [  1.  , 207.  ,  21.72,  36.84],
       [  1.  , 102.84,  42.96,  59.16],
       [  1.  , 226.08,  21.72,  30.72],
       [  1.  , 196.2 ,  44.16,   8.88],
       [  1.  , 140.64,  17.64,   6.48],
       [  1.  , 281.4 ,   4.08, 101.76],
       [  1.  ,  21.48,  45.12,  25.92],
       [  1.  , 248.16,   6.24,  23.28],
       [  1.  , 258.48,  28.32,  69.12],
       [  1.  , 341.16,  12.72,   7.68],
       [  1.  ,  60.  ,  13.92,  22.08],
       [  1.  , 197.4 ,  25.08,  56.88],
       [  1.  ,  23.52,  24.12,  20.4 ],
       [  1.  , 202.08,   8.52,  15.36],
       [  1.  , 266.88,   4.08,  15.72],
       [  1.  , 332.28,  58.68,  50.16],
       [  1.  , 298.08,  36.24,  24.36],
       [  1.  , 204.24,   9.36,  42.24],
       [  1.  , 332.04,   2.76,  28.44],
       [  1.  , 198.72,  12.  ,  21.12],
       [  1.  , 187.92,   3.12,   9.96],
       [  1.  , 262.2 ,   6.48,  32.88],
       [  1.  ,  67.44,   6.84,  35.64],
       [  1.  , 345.12,  51.6 ,  86.16],
       [  1.  , 304.56,  25.56,  36.  ],
       [  1.  , 246.  ,  54.12,  23.52],
       [  1.  , 167.4 ,   2.52,  31.92],
       [  1.  , 229.32,  34.44,  21.84],
       [  1.  , 343.2 ,  16.68,   4.44],
       [  1.  ,  22.44,  14.52,  28.08],
       [  1.  ,  47.4 ,  49.32,   6.96],
       [  1.  ,  90.6 ,  12.96,   7.2 ],
       [  1.  ,  20.64,   4.92,  37.92],
       [  1.  , 200.16,  50.4 ,   4.32],
       [  1.  , 179.64,  42.72,   7.2 ],
       [  1.  ,  45.84,   4.44,  16.56],
       [  1.  , 113.04,   5.88,   9.72],
       [  1.  , 212.4 ,  11.16,   7.68],
       [  1.  , 340.32,  50.4 ,  79.44],
       [  1.  , 278.52,  10.32,  10.44]])

(X*X(T))-1*(X(t)*y

In [34]:
x_transpose=np.transpose(final)

In [35]:
x_transpose

array([[  1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ],
       [ 84.72, 351.48, 135.48, 116.64, 318.72, 114.84, 348.84, 320.28,
         89.64,  51.72, 273.6 , 243.  , 212.4 , 352.32, 248.28,  30.12,
        210.12, 107.64, 287.88, 272.64,  80.28, 239.76, 120.48, 259.68,
        219.12, 315.24, 238.68,   8.76, 163.44, 252.96, 252.84,  64.2 ,
        313.56, 287.16, 123.24, 157.32,  82.8 ,  37.8 , 167.16, 284.88,
        260.16, 238.92, 131.76,  32.16, 155.28, 256.08,  20.28,  33.  ,
        144.6 ,   6.48, 139.2 ,  91.68, 287.76,  90.36,  82.08, 256.2 ,
        231.84,  91.56, 132.84, 105.96, 131.76, 161.16,  34.32, 261.24,
        301.08, 128.88, 195.96, 237.12, 221.88, 347.64, 162.24, 266.88,
        355.68, 336.24, 225.48, 285.84, 165.48,  30.  , 108.48,  15.72,
        306.48, 270.96, 290.04, 210.84, 251.52,  93.84,  90.12, 167.04,
         91.68, 150.84,  23.28, 169.56,  22.56, 268.8 , 147.72, 275.4 ,
        104.64,   9.36,  96.24, 264.36,  71.52,   0.84, 318.24,  10.08,
        263.76,  44.28,  57.96,  30.72, 328.44,  51.6 , 221.88,  88.08,
        232.44, 264.6 , 125.52, 115.44, 168.36, 288.12, 291.84,  45.6 ,
         53.64, 336.84, 145.2 , 237.12, 205.56, 225.36,   4.92, 112.68,
        179.76,  14.04, 158.04, 207.  , 102.84, 226.08, 196.2 , 140.64,
        281.4 ,  21.48, 248.16, 258.48, 341.16,  60.  , 197.4 ,  23.52,
        202.08, 266.88, 332.28, 298.08, 204.24, 332.04, 198.72, 187.92,
        262.2 ,  67.44, 345.12, 304.56, 246.  , 167.4 , 229.32, 343.2 ,
         22.44,  47.4 ,  90.6 ,  20.64, 200.16, 179.64,  45.84, 113.04,
        212.4 , 340.32, 278.52],
       [ 19.2 ,  33.96,  20.88,   1.8 ,  24.  ,   1.68,   4.92,  52.56,
         59.28,  32.04,  45.24,  26.76,  40.08,  33.24,  10.08,  30.84,
         27.  ,  11.88,  49.8 ,  18.96,  14.04,   3.72,  11.52,  50.04,
         55.44,  34.56,  59.28,  33.72,  23.04,  59.52,  35.4 ,   2.4 ,
         51.24,  18.6 ,  35.52,  51.36,  11.16,  29.52,  17.4 ,  33.  ,
         52.68,  36.72,  17.16,  39.6 ,   6.84,  29.52,  52.44,   1.92,
         34.2 ,  35.88,   9.24,  32.04,   4.92,  24.36,  53.4 ,  51.6 ,
         22.08,  33.  ,  48.72,  30.6 ,  57.36,   5.88,   1.8 ,  40.2 ,
         43.8 ,  16.8 ,  37.92,   4.2 ,  25.2 ,  50.76,  50.04,   5.16,
         43.56,  12.12,  20.64,  41.16,  55.68,  13.2 ,   0.36,   0.48,
         32.28,   9.84,  45.6 ,  18.48,  24.72,  56.16,  42.  ,  17.16,
          0.96,  44.28,  19.2 ,  32.16,  26.04,   2.88,  41.52,  38.76,
         14.16,  46.68,   0.  ,  58.8 ,  14.4 ,  47.52,   3.48,  32.64,
         40.2 ,  46.32,  56.4 ,  46.8 ,  34.68,  31.08,  52.68,  20.4 ,
         42.48,  39.84,   6.84,  17.76,   2.28,   8.76,  58.8 ,  48.36,
         30.96,  16.68,  10.08,  27.96,  47.64,  25.32,  13.92,  52.2 ,
          1.56,  44.28,  22.08,  21.72,  42.96,  21.72,  44.16,  17.64,
          4.08,  45.12,   6.24,  28.32,  12.72,  13.92,  25.08,  24.12,
          8.52,   4.08,  58.68,  36.24,   9.36,   2.76,  12.  ,   3.12,
          6.48,   6.84,  51.6 ,  25.56,  54.12,   2.52,  34.44,  16.68,
         14.52,  49.32,  12.96,   4.92,  50.4 ,  42.72,   4.44,   5.88,
         11.16,  50.4 ,  10.32],
       [ 48.96,  51.84,  46.32,  36.  ,   0.36,   8.88,  10.2 ,   6.  ,
         54.84,  42.12,  38.4 ,  37.92,  46.44,   2.16,  31.68,  51.96,
         37.8 ,  42.84,  22.2 ,  59.88,  44.16,  41.52,   4.32,  47.52,
         70.44,  19.08,  72.  ,  49.68,  19.92,  45.24,  11.16,  25.68,
         65.64,  32.76,  10.08,  34.68,   1.08,   2.64,  12.24,  13.2 ,
         32.64,  46.44,  38.04,  23.16,  37.56,  15.72, 107.28,  24.84,
         17.04,  11.28,  27.72,  26.76,  44.28,  39.  ,  42.72,  40.56,
         78.84,  19.2 ,  75.84,  88.08,  61.68,  11.16,  39.6 ,  70.8 ,
         86.76,  13.08,  63.48,   7.08,  26.4 ,  61.44,  55.08,  59.76,
        121.08,  25.68,  21.48,   6.36,  70.8 ,  35.64,  27.84,  30.72,
          6.6 ,  67.8 ,  27.84,   2.88,  12.84,  41.4 ,  63.24,  30.72,
         17.76,  95.04,  26.76,  55.44,  60.48,  18.72,  14.88,  89.04,
         31.08,  60.72,  11.04,   3.84,  51.72,  10.44,  51.6 ,   2.52,
         54.12,  78.72,  10.2 ,  11.16,  71.64,  24.6 ,   2.04,  15.48,
         90.72,  45.48,  41.28,  46.68,  10.8 ,  10.44,  53.16,  14.28,
         24.72,  44.4 ,  58.44,  17.04,  45.24,  11.4 ,   6.84,  60.6 ,
         29.16,  54.24,  41.52,  36.84,  59.16,  30.72,   8.88,   6.48,
        101.76,  25.92,  23.28,  69.12,   7.68,  22.08,  56.88,  20.4 ,
         15.36,  15.72,  50.16,  24.36,  42.24,  28.44,  21.12,   9.96,
         32.88,  35.64,  86.16,  36.  ,  23.52,  31.92,  21.84,   4.44,
         28.08,   6.96,   7.2 ,  37.92,   4.32,   7.2 ,  16.56,   9.72,
          7.68,  79.44,  10.44]])

In [36]:
first_op=(x_transpose@final) #first operand (xT*x)

array([[1.71000000e+02, 3.04416000e+04, 4.73184000e+03, 6.02604000e+03],
       [3.04416000e+04, 7.20355208e+06, 8.69366232e+05, 1.12080054e+06],
       [4.73184000e+03, 8.69366232e+05, 1.85489568e+05, 1.89002506e+05],
       [6.02604000e+03, 1.12080054e+06, 1.89002506e+05, 3.17784053e+05]])

In [40]:
first_op=np.linalg.inv(first_op)

In [41]:
first_op

array([[ 3.95364413e-02, -8.83018573e-05, -3.75982708e-04,
        -2.14666950e-04],
       [-8.83018573e-05,  5.69244048e-07, -1.92501263e-07,
        -2.18750098e-07],
       [-3.75982708e-04, -1.92501263e-07,  2.01231733e-05,
        -4.15970472e-06],
       [-2.14666950e-04, -2.18750098e-07, -4.15970472e-06,
         1.04629589e-05]])

In [42]:
second_op=x_transpose@y

In [43]:
second_op

array([  2893.8   , 601163.3664,  91670.0544, 108794.0448])

In [49]:
newTheta=first_op.dot(second_op)   #xt*x-1 * xt*y    newTheta

In [48]:

def simpleNormalEquation(theta1,theta2,theta3,yt,fb,nb,theta0):
  line=theta1*yt+theta2*fb+theta3*nb+theta0
  print(line)

In [52]:
simpleNormalEquation(newTheta[1],newTheta[2],newTheta[3],84,19,48,newTheta[0])

11.090622617161099